// actions
export const FETCH_ALL_NEWS = "FETCH_ALL_NEWS";
export const FETCH_FOREX_NEWS = "FETCH_FOREX_NEWS";
export const FETCH_COMMIDITIES_NEWS = "FETCH_COMMIDITIES_NEWS";
export const FETCH_STOCK_MARKET_NEWS = "FETCH_STOCK_MARKET_NEWS";
export const FETCH_ECONOMIC_INDICATOR_NEWS = "FETCH_ECONOMIC_INDICATOR_NEWS";
export const FETCH_ECONOMY_NEWS = "FETCH_ECONOMY_NEWS";
export const FETCH_CRYPTO_CURRENCY_NEWS = "FETCH_CRYPTO_CURRENCY_NEWS";

// mutations
export const SET_ALL_NEWS = "SET_ALL_NEWS";
export const SET_FOREX_NEWS = "SET_FOREX_NEWS";
export const SET_COMMIDITIES_NEWS = "SET_COMMIDITIES_NEWS";
export const SET_STOCK_MARKET_NEWS = "SET_STOCK_MARKET_NEWS";
export const SET_ECONOMIC_INDICATOR_NEWS = "SET_ECONOMIC_INDICATOR_NEWS";
export const SET_ECONOMY_NEWS = "SET_ECONOMY_NEWS";
export const SET_CRYPTO_CURRENCY_NEWS = "SET_CRYPTO_CURRENCY_NEWS";

export const UNSET_ALL_NEWS = "UNSET_ALL_NEWS";
export const UNSET_FOREX_NEWS = "UNSET_FOREX_NEWS";
export const UNSET_COMMIDITIES_NEWS = "UNSET_COMMIDITIES_NEWS";
export const UNSET_STOCK_MARKET_NEWS = "UNSET_STOCK_MARKET_NEWS";
export const UNSET_ECONOMIC_INDICATOR_NEWS = "UNSET_ECONOMIC_INDICATOR_NEWS";
export const UNSET_ECONOMY_NEWS = "UNSET_ECONOMY_NEWS";
export const UNSET_CRYPTO_CURRENCY_NEWS = "UNSET_CRYPTO_CURRENCY_NEWS";

// getters
export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const GET_FOREX_NEWS = "GET_FOREX_NEWS";
export const GET_COMMIDITIES_NEWS = "GET_COMMIDITIES_NEWS";
export const GET_STOCK_MARKET_NEWS = "GET_STOCK_MARKET_NEWS";
export const GET_ECONOMIC_INDICATOR_NEWS = "GET_ECONOMIC_INDICATOR_NEWS";
export const GET_ECONOMY_NEWS = "GET_ECONOMY_NEWS";
export const GET_CRYPTO_CURRENCY_NEWS = "GET_CRYPTO_CURRENCY_NEWS";
